logging:
  level:
    dev.temez.demo.service.user: debug
  file:
    name: ./logs/${spring.application.name:unknown-service}.log

spring:
  datasource:
    username: username
    password: password
    url: jdbc:sqlite:identifier.sqlite
    driver-class-name: org.sqlite.JDBC

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect